### PR TITLE
conn: fix racy access to result fields when connection is closing

### PR DESCRIPTION
**Pull request by jdef**
With the introduction of #3 there's now a potential race, at connection close time, between the "send handler" that mutates response objects, and the `return` statements of top-level API calls that read response fields. This PR checks for the race and returns a "connection closing" error in such cases.

### CODE REVIEW

**Comment by mhrabovcin** [comment]
As suggested online @jdef . Is there a possibility to put this single `select` statement into `request` method?

I can see the need to add special error handler here https://github.com/mesosphere/go-zookeeper/pull/4/files#diff-5f455e42d3680fdc56c7076dc0c182f3R1332 but the rest of the code just passes error to the caller.

**Comment by mhrabovcin** [comment]
@jdef thanks for the detailed explanation. I don't have a **strong** preference here.  From the code readability perspective I think it would be nice to handle this case with the single `select` statement and a comment that would explain why is this necessary. All the callers can then handle `ErrConnectionClosed` depending on data use.

I am happy to approve the code as it is!

**Comment by jdef** [comment]
squashed prior to merge

**Comment by jdef** [comment]
possibly racy test?
```
--- FAIL: TestDNSHostProviderReconnect (2.49s)
	cluster_test.go:15: [ZKERR] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
	cluster_test.go:15: [ZKERR] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
	cluster_test.go:15: [ZKERR] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
	dnshostprovider_test.go:130: Connected to "localhost:11657". Finding test server index…
	dnshostprovider_test.go:134: …trying "localhost:11657"
	dnshostprovider_test.go:137: …found at index 0
	dnshostprovider_test.go:151: Create returned error: zk: connection closed
	cluster_test.go:15: [ZKERR] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
```

**Pull request merged**
